spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:rundb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  liquibase:
    enabled: false
