spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:rundb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/changeset-master.yml
#logging:
#  file: logs/dev_profile_app.log
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.controllers: DEBUG
#    org.hibernate: DEBUG