spring:
  application:
    name: Family-Service
server:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/FamilyCert.p12
    key-store-password: RyxJaFuQ3uZXwD82nFgKtWUfBfuekmJB
    key-alias: FamilyCert
    enabled: true
  port: 8082
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/