spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changeset-master.yml
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: mysql://${MYSQL_HOST:localhost}:3306/myDb
    username: root
    password: 123