spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changeset-master.yml
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    #    url: mysql://${MYSQL_HOST:localhost}:3306/myDb
    url: jdbc:mysql://192.168.0.15:3306/PreProdDB
    username: root
    password: password
